version: '3.8'
services:
  postgres:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
  redis:
    image: redis:6.0.3-alpine
    ports:
      - 6379:6379
